package reporter

import (
	"fmt"
	"html/template"
	"os"
	"sql-check/internal/model"
	"time"
)

type HTMLReporter struct {
	OutputFile string
}

func NewHTMLReporter(filename string) *HTMLReporter {
	return &HTMLReporter{OutputFile: filename}
}

const htmlTemplate = `
<!DOCTYPE html>
<html>
<head>
	<title>SQL Usage Report</title>
	<style>
		body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 20px; background: #f4f6f8; color: #333; }
		.container { max-width: 1000px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.05); }
		h1 { border-bottom: 2px solid #eee; padding-bottom: 10px; }
		.summary { margin-bottom: 30px; padding: 15px; background: #eef2f5; border-radius: 5px; }
		.issue { border: 1px solid #eee; border-radius: 5px; margin-bottom: 15px; overflow: hidden; }
		.issue-header { padding: 10px 15px; display: flex; justify-content: space-between; align-items: center; cursor: pointer; }
		.FATAL { background-color: #ffebee; border-left: 5px solid #d32f2f; }
		.WARNING { background-color: #fff8e1; border-left: 5px solid #ffa000; }
		.SUGGESTION { background-color: #e3f2fd; border-left: 5px solid #1976d2; }
		.issue-body { padding: 15px; display: block; border-top: 1px solid #eee; background: #fff; }
		.code-block { background: #282c34; color: #abb2bf; padding: 10px; border-radius: 4px; font-family: monospace; overflow-x: auto; }
		.location { font-size: 0.9em; color: #666; margin-bottom: 5px; }
		.suggestion { font-weight: bold; color: #2e7d32; margin-top: 10px; }
		.meta { font-size: 0.85rem; color: #777; margin-top: 20px; text-align: center; }
	</style>
</head>
<body>
	<div class="container">
		<h1>SQL Scan Report</h1>
		<div class="summary">
			<strong>Scan Date:</strong> {{ .Date }}<br>
			<strong>Total Issues:</strong> {{ .TotalCount }}
		</div>

		{{ range .Issues }}
		<div class="issue">
			<div class="issue-header {{ .Level }}">
				<span><strong>[{{ .Level }}]</strong> {{ .Type }}</span>
				<span class="location">{{ .Segment.Location }}</span>
			</div>
			<div class="issue-body">
				<div class="message">{{ .Message }}</div>
				<pre class="code-block">{{ .Segment.SQL }}</pre>
				<div class="suggestion">💡 Suggestion: {{ .Suggestion }}</div>
			</div>
		</div>
		{{ else }}
		<div style="text-align: center; padding: 50px; color: #2e7d32;">
			<h2>🎉 Codebase is Clean!</h2>
			<p>No SQL issues found.</p>
		</div>
		{{ end }}
		
		<div class="meta">Generated by SQL-Check Tool</div>
	</div>
</body>
</html>
`

type reportData struct {
	Date       string
	TotalCount int
	Issues     []model.Issue
}

func (r *HTMLReporter) Report(issues []model.Issue) error {
	f, err := os.Create(r.OutputFile)
	if err != nil {
		return err
	}
	defer f.Close()

	t, err := template.New("report").Parse(htmlTemplate)
	if err != nil {
		return err
	}

	data := reportData{
		Date:       time.Now().Format(time.RFC1123),
		TotalCount: len(issues),
		Issues:     issues,
	}

	if err := t.Execute(f, data); err != nil {
		return err
	}

	fmt.Printf("Report generated: %s\n", r.OutputFile)
	return nil
}
